/**
 * Uygulama genelinde kullanılan sabitler
 */

export const APP_CONFIG = {
  APP_NAME: 'Turizm Pazaryeri',
  API_PREFIX: '/api',
  DEFAULT_CURRENCY: 'TRY' as const,
  DEFAULT_LANGUAGE: 'tr' as const,

  // Pagination
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,

  // JWT
  ACCESS_TOKEN_TTL_SECONDS: 15 * 60, // 15 dk
  REFRESH_TOKEN_TTL_SECONDS: 30 * 24 * 60 * 60, // 30 gün
  REFRESH_TOKEN_FAMILY_LENGTH: 16,
} as const;

/**
 * İş kuralı sabitleri
 */
export const BUSINESS_RULES = {
  MIN_RATING: 1,
  MAX_RATING: 5,
  MIN_PARTICIPANT_COUNT: 1,
  MAX_PARTICIPANT_COUNT: 100,
  RESERVATION_CODE_LENGTH: 12,
  COUPON_CODE_MAX_LENGTH: 50,
  TAX_NUMBER_LENGTH: 11, // TC vatandaşlık no; VKN 10 hane — validasyon DTO'da yapılır
  IMAGE_SORT_MAIN_PRIORITY: 0,
  DEFAULT_PAGE_SIZE: 20,
  SEARCH_MIN_LENGTH: 2,
  SEARCH_MAX_LENGTH: 100,
} as const;

/**
 * Hata kodları (API yanıtlarında kullanılır)
 */
export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_USER_BANNED: 'AUTH_USER_BANNED',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',

  // Authorization
  ROLE_FORBIDDEN: 'ROLE_FORBIDDEN',
  OWNERSHIP_VIOLATION: 'OWNERSHIP_VIOLATION',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Business
  CAPACITY_EXCEEDED: 'CAPACITY_EXCEEDED',
  SCHEDULE_CLOSED: 'SCHEDULE_CLOSED',
  RESERVATION_NOT_CANCELLABLE: 'RESERVATION_NOT_CANCELLABLE',
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_USAGE_LIMIT_REACHED: 'COUPON_USAGE_LIMIT_REACHED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',

  // Internal
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  THIRD_PARTY_ERROR: 'THIRD_PARTY_ERROR',
} as const;

/**
 * HTTP durum kodları için yardımcı sabitler
 */
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

/**
 * Slug üretiminde yalnızca izin verilen karakterler
 */
export const SLUG_ALLOWED_PATTERN = /^[a-z0-9-]+$/;

/**
 * Şehir ve kategori slug'ları için benzersiz önek uzunluğu (collision-free kısaltma)
 */
export const SLUG_HASH_LENGTH = 6;
